In [1]:
from astropy.io import fits
fits_image_filename = fits.util.get_testdata_filepath('test0.fits')

hdul = fits.open(fits_image_filename)

In [2]:
hdul.info()

Filename: /opt/anaconda3/lib/python3.9/site-packages/astropy/io/fits/tests/data/test0.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU     138   ()      
  1  SCI           1 ImageHDU        61   (40, 40)   int16   
  2  SCI           2 ImageHDU        61   (40, 40)   int16   
  3  SCI           3 ImageHDU        61   (40, 40)   int16   
  4  SCI           4 ImageHDU        61   (40, 40)   int16   


In [3]:
hdul.close()

In [4]:
with fits.open(fits_image_filename) as hdul:
    hdul.info()

Filename: /opt/anaconda3/lib/python3.9/site-packages/astropy/io/fits/tests/data/test0.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU     138   ()      
  1  SCI           1 ImageHDU        61   (40, 40)   int16   
  2  SCI           2 ImageHDU        61   (40, 40)   int16   
  3  SCI           3 ImageHDU        61   (40, 40)   int16   
  4  SCI           4 ImageHDU        61   (40, 40)   int16   


In [8]:
with fits.open(fits_image_filename) as hdul:
   hdul.verify('fix')
   data = hdul[1].data

In [9]:
hdul = fits.open(fits_image_filename)
hdul[0].header['DATE']

'01/04/99'

In [10]:
hdul[0].header[7]

32768.0

In [11]:
hdr = hdul[0].header
hdr['targname'] = 'NGC121-a'
hdr[27] = 99

In [12]:
hdr = hdul[0].header
hdr['targname'] = ('NGC121-a', 'the observation target')
hdr['targname']

hdr.comments['targname']


'the observation target'

In [13]:
hdr.set('observer', 'Edwin Hubble')

In [14]:
hdr['history'] = 'I updated this file 2/26/09'
hdr['comment'] = 'Edwin Hubble really knew his stuff'
hdr['comment'] = 'I like using HST observations'
hdr['history']

hdr['comment']


Edwin Hubble really knew his stuff
I like using HST observations

In [15]:
hdr['history'][0] = 'I updated this file on 2/27/09'
hdr['history']

hdr['comment'][1] = 'I like using JWST observations'
hdr['comment']


Edwin Hubble really knew his stuff
I like using JWST observations

In [16]:
hdr  




print(repr(hdr)) 

SIMPLE  =                    T / file does conform to FITS standard             
BITPIX  =                   16 / number of bits per data pixel                  
NAXIS   =                    0 / number of data axes                            
EXTEND  =                    T / FITS dataset may contain extensions            
GROUPS  =                    F / data has groups                                
NEXTEND =                    4 / Number of standard extensions                  
BSCALE  =           1.000000E0 / REAL = TAPE*BSCALE + BZERO                     
BZERO   =           3.276800E4 /                                                
ORIGIN  = 'NOAO-IRAF FITS Image Kernel Aug 1 1997' / FITS file originator       
DATE    = '01/04/99  '         / Date FITS file was generated                   
IRAF-TLM= 'xxx     '              / Time of last modification                   
                                                                                
              / GROUP PARAME

In [17]:
hdr[:2]

SIMPLE  =                    T / file does conform to FITS standard             
BITPIX  =                   16 / number of bits per data pixel                  

In [18]:
list(hdr.keys())

['SIMPLE',
 'BITPIX',
 'NAXIS',
 'EXTEND',
 'GROUPS',
 'NEXTEND',
 'BSCALE',
 'BZERO',
 'ORIGIN',
 'DATE',
 'IRAF-TLM',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 'INSTRUME',
 'ROOTNAME',
 'FILETYPE',
 '',
 '',
 'MODE',
 'SERIALS',
 '',
 '',
 'IMAGETYP',
 'CDBSFILE',
 'PKTFMT',
 '',
 '',
 'FILTNAM1',
 'FILTNAM2',
 'FILTER1',
 'FILTER2',
 'FILTROT',
 'LRFWAVE',
 '',
 '',
 'UCH1CJTM',
 'UCH2CJTM',
 'UCH3CJTM',
 'UCH4CJTM',
 'UBAY3TMP',
 'KSPOTS',
 'SHUTTER',
 'ATODGAIN',
 '',
 '',
 'MASKCORR',
 'ATODCORR',
 'BLEVCORR',
 'BIASCORR',
 'DARKCORR',
 'FLATCORR',
 'SHADCORR',
 'DOSATMAP',
 'DOPHOTOM',
 'DOHISTOS',
 'OUTDTYPE',
 '',
 '',
 'MASKFILE',
 'ATODFILE',
 'BLEVFILE',
 'BLEVDFIL',
 'BIASFILE',
 'BIASDFIL',
 'DARKFILE',
 'DARKDFIL',
 'FLATFILE',
 'FLATDFIL',
 'SHADFILE',
 'PHOTTAB',
 'GRAPHTAB',
 'COMPTAB',
 '',
 '',
 'SATURATE',
 'USCALE',
 'UZERO',
 '',
 '',
 'READTIME',
 '',
 '',
 'PA_V3',
 'RA_SUN',
 'DEC_SUN',
 'EQNX_SUN',
 'MTFLAG',
 'EQRADTRG',
 'FLATNTRG',
 'NPD

In [19]:
data = hdul[1].data

In [20]:
data = hdul['SCI'].data

In [21]:
data = hdul['sci',2].data

In [22]:
data.shape

data.dtype.name

'int16'

In [23]:
data.shape

(40, 40)

In [24]:
print(data[1, 4])

348


In [25]:
data[30:40, 10:20]

array([[350, 349, 349, 348, 349, 348, 349, 347, 350, 348],
       [348, 348, 348, 349, 348, 349, 347, 348, 348, 349],
       [348, 348, 347, 349, 348, 348, 349, 349, 349, 349],
       [349, 348, 349, 349, 350, 349, 349, 347, 348, 348],
       [348, 348, 348, 348, 349, 348, 350, 349, 348, 349],
       [348, 347, 349, 349, 350, 348, 349, 348, 349, 347],
       [347, 348, 347, 348, 349, 349, 350, 349, 348, 348],
       [349, 349, 350, 348, 350, 347, 349, 349, 349, 348],
       [349, 348, 348, 348, 348, 348, 349, 347, 349, 348],
       [349, 349, 349, 348, 350, 349, 349, 350, 348, 350]], dtype=int16)

In [26]:
data[30:40, 10:20] = data[1, 4] = 999

In [27]:
photflam = hdul[1].header['photflam']
exptime = hdr['exptime']
data = data * photflam / exptime
hdul.close()

In [28]:
fits_table_filename = fits.util.get_testdata_filepath('tb.fits')
hdul = fits.open(fits_table_filename)
data = hdul[1].data # assuming the first extension is a table
hdul.close()

In [29]:
print(data[0])

(1, 'abc', 3.7000000715255736, False)


In [30]:
data.field(0)

array([1, 2], dtype=int32)

In [31]:
data.field('c1')

array([1, 2], dtype=int32)

In [32]:
data['c1']

array([1, 2], dtype=int32)

In [33]:
cols = hdul[1].columns

In [34]:
cols.info()

name:
    ['c1', 'c2', 'c3', 'c4']
format:
    ['1J', '3A', '1E', '1L']
unit:
    ['', '', '', '']
null:
    [-2147483647, '', '', '']
bscale:
    ['', '', 3, '']
bzero:
    ['', '', 0.4, '']
disp:
    ['I11', 'A3', 'G15.7', 'L6']
start:
    ['', '', '', '']
dim:
    ['', '', '', '']
coord_type:
    ['', '', '', '']
coord_unit:
    ['', '', '', '']
coord_ref_point:
    ['', '', '', '']
coord_ref_value:
    ['', '', '', '']
coord_inc:
    ['', '', '', '']
time_ref_pos:
    ['', '', '', '']


In [35]:
hdul[1].columns

ColDefs(
    name = 'c1'; format = '1J'; null = -2147483647; disp = 'I11'
    name = 'c2'; format = '3A'; disp = 'A3'
    name = 'c3'; format = '1E'; bscale = 3; bzero = 0.4; disp = 'G15.7'
    name = 'c4'; format = '1L'; disp = 'L6'
)

In [36]:
cols.names

['c1', 'c2', 'c3', 'c4']

In [37]:
data['c4'][:] = 0

In [38]:
data['c3'].mean()  

5.19999989271164

In [39]:
hdul.writeto('newtable.fits')

ValueError: I/O operation on closed file

In [41]:
import numpy as np
n = np.arange(100.0) # a simple sequence of floats from 0.0 to 99.9

In [42]:
hdu = fits.PrimaryHDU(n)

In [43]:
hdul = fits.HDUList([hdu])
hdul.writeto('new1.fits')

In [44]:
hdu.writeto('new2.fits')

In [45]:
from astropy.table import Table
t = Table([[1, 2], [4, 5], [7, 8]], names=('a', 'b', 'c'))
t.write('table1.fits', format='fits')

In [46]:
from astropy.io import fits
import numpy as np
c1 = fits.Column(name='a', array=np.array([1, 2]), format='K')
c2 = fits.Column(name='b', array=np.array([4, 5]), format='K')
c3 = fits.Column(name='c', array=np.array([7, 8]), format='K')
t = fits.BinTableHDU.from_columns([c1, c2, c3])
t.writeto('table2.fits')

In [47]:
import numpy as np
a1 = np.array(['NGC1001', 'NGC1002', 'NGC1003'])
a2 = np.array([11.1, 12.3, 15.2])
col1 = fits.Column(name='target', format='20A', array=a1)
col2 = fits.Column(name='V_mag', format='E', array=a2)

In [48]:
cols = fits.ColDefs([col1, col2])

In [49]:
hdu = fits.BinTableHDU.from_columns(cols)

In [50]:
hdu = fits.BinTableHDU.from_columns(
    [fits.Column(name='target', format='20A', array=a1),
     fits.Column(name='V_mag', format='E', array=a2)])

In [51]:
hdu.writeto('table3.fits')

In [52]:
import numpy as np
n = np.ones((3, 3))
n2 = np.ones((100, 100))
n3 = np.ones((10, 10, 10))

In [53]:
primary_hdu = fits.PrimaryHDU(n)
image_hdu = fits.ImageHDU(n2)
image_hdu2 = fits.ImageHDU(n3)

In [54]:
c1 = fits.Column(name='a', array=np.array([1, 2]), format='K')
c2 = fits.Column(name='b', array=np.array([4, 5]), format='K')
c3 = fits.Column(name='c', array=np.array([7, 8]), format='K')
table_hdu = fits.BinTableHDU.from_columns([c1, c2, c3])

In [55]:
hdul = fits.HDUList([primary_hdu, image_hdu, table_hdu])

In [56]:
hdul.append(image_hdu2)

In [57]:
hdr = fits.Header()
hdr['OBSERVER'] = 'Edwin Hubble'
hdr['COMMENT'] = "Here's some commentary about this FITS file."
empty_primary = fits.PrimaryHDU(header=hdr)

In [58]:
hdul = fits.HDUList([empty_primary, image_hdu2, table_hdu])

In [59]:
from astropy.io.fits import getheader
hdr = getheader(fits_image_filename)  # get default HDU (=0), i.e. primary HDU's header
hdr = getheader(fits_image_filename, 0)  # get primary HDU's header
hdr = getheader(fits_image_filename, 2)  # the second extension
hdr = getheader(fits_image_filename, 'sci')  # the first HDU with EXTNAME='SCI'
hdr = getheader(fits_image_filename, 'sci', 2)  # HDU with EXTNAME='SCI' and EXTVER=2
hdr = getheader(fits_image_filename, ('sci', 2))  # use a tuple to do the same
hdr = getheader(fits_image_filename, ext=2)  # the second extension
hdr = getheader(fits_image_filename, extname='sci')  # first HDU with EXTNAME='SCI'
hdr = getheader(fits_image_filename, extname='sci', extver=2)

In [60]:
getheader(fits_image_filename, ext=('sci', 1), extname='err', extver=2)


TypeError: Redundant/conflicting extension arguments(s): {'args': (), 'ext': ('sci', 1), 'extname': 'err', 'extver': 2}

In [61]:
fits_image_2_filename = fits.util.get_testdata_filepath('o4sp040b0_raw.fits')
hdr = getheader(fits_image_2_filename, 0)    # get primary hdu's header
filter = hdr['filter']                       # get the value of the keyword "filter'
val = hdr[10]                                # get the 11th keyword's value
hdr['filter'] = 'FW555'                      # change the keyword value

In [62]:
from astropy.io.fits import getval
# get 0th extension's keyword FILTER's value
flt = getval(fits_image_2_filename, 'filter', 0)
flt


# get the 2nd sci extension's 11th keyword's value
val = getval(fits_image_2_filename, 10, 'sci', 2)
val

False

In [63]:
from astropy.io.fits import getdata
# get 3rd sci extension's data:
data = getdata(fits_image_filename, 'sci', 3)
# get 1st extension's data AND header:
data, hdr = getdata(fits_image_filename, 1, header=True)

In [64]:
fits.writeto('out.fits', data, hdr)

In [65]:
fits.append('out.fits', data, hdr)

In [66]:
from astropy.io.fits import update
update(filename, dat, hdr, 'sci')         # update the 'sci' extension
update(filename, dat, 3)                  # update the 3rd extension
update(filename, dat, hdr, 3)             # update the 3rd extension
update(filename, dat, 'sci', 2)           # update the 2nd SCI extension
update(filename, dat, 3, header=hdr)      # update the 3rd extension
update(filename, dat, header=hdr, ext=5)  # update the 5th extension

NameError: name 'filename' is not defined

In [67]:
from astropy.io.fits import printdiff
# get a difference report of ext 2 of inA and inB
printdiff('inA.fits', 'inB.fits', ext=2)
# ignore HISTORY and COMMENT keywords
printdiff('inA.fits', 'inB.fits', ignore_keywords=('HISTORY','COMMENT')

SyntaxError: unexpected EOF while parsing (1428782923.py, line 5)

In [68]:
fits.info(fits_image_filename)

Filename: /opt/anaconda3/lib/python3.9/site-packages/astropy/io/fits/tests/data/test0.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU     138   ()      
  1  SCI           1 ImageHDU        61   (40, 40)   int16   
  2  SCI           2 ImageHDU        61   (40, 40)   int16   
  3  SCI           3 ImageHDU        61   (40, 40)   int16   
  4  SCI           4 ImageHDU        61   (40, 40)   int16   


In [69]:
import dask.array as da
array = da.random.random((1000, 1000))
from astropy.io import fits
hdu = fits.PrimaryHDU(data=array)
hdu.writeto('test_dask.fits')

In [2]:
from astropy.table import Table
t = Table()
t['a'] = [1, 2, 3, 4]
t['b'] = ['a', 'b', 'c', 'd']

In [3]:
df = t.to_pandas()
df





type(df)

pandas.core.frame.DataFrame

In [4]:
t2 = Table.from_pandas(df)
t2

<Table length=4>
  a    b  
int64 str1
----- ----
    1    a
    2    b
    3    c
    4    d